//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cornershop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cornershopEntities : DbContext
    {
        public cornershopEntities()
            : base("name=cornershopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boleta> boletas { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<DetalleOrdenPedido> DetalleOrdenPedidoes { get; set; }
        public virtual DbSet<distrito> distritoes { get; set; }
        public virtual DbSet<OrdenPedido> OrdenPedidoes { get; set; }
        public virtual DbSet<pago> pagoes { get; set; }
        public virtual DbSet<presentacion> presentacions { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<shooper> shoopers { get; set; }
        public virtual DbSet<tienda> tiendas { get; set; }
        public virtual DbSet<tipoPago> tipoPagoes { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<CATEGORIA_TIENDA> CATEGORIA_TIENDA { get; set; }
        public virtual DbSet<PAI> PAIS { get; set; }
    }
}
