//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cornershop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public string cod_pago { get; set; }
        public string cod_tipoPago { get; set; }
        public string cod_cli { get; set; }
        public string numTarjeta { get; set; }
        public int mm { get; set; }
        public int aa { get; set; }
        public string cvc { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual tipoPago tipoPago { get; set; }
    }
}
