//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cornershop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleOrdenPedidoes = new HashSet<DetalleOrdenPedido>();
        }
    
        public string cod_pro { get; set; }
        public string nom_pro { get; set; }
        public decimal pre_venta { get; set; }
        public int stock { get; set; }
        public string cod_cate { get; set; }
        public string cod_tie { get; set; }
        public string cod_pres { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleOrdenPedido> DetalleOrdenPedidoes { get; set; }
        public virtual presentacion presentacion { get; set; }
        public virtual tienda tienda { get; set; }
    }
}
