//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cornershop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shooper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shooper()
        {
            this.OrdenPedidoes = new HashSet<OrdenPedido>();
            this.OrdenPedidoes1 = new HashSet<OrdenPedido>();
        }
    
        public string cod_shop { get; set; }
        public string nom_shop { get; set; }
        public string dir_shop { get; set; }
        public string cod_dis { get; set; }
        public string edad { get; set; }
        public int tel { get; set; }
        public Nullable<int> cel { get; set; }
        public string email { get; set; }
        public string cod_usu { get; set; }
    
        public virtual distrito distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenPedido> OrdenPedidoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenPedido> OrdenPedidoes1 { get; set; }
    }
}
