//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cornershop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tienda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tienda()
        {
            this.Productoes = new HashSet<Producto>();
        }
    
        public string cod_tie { get; set; }
        public string nom_tie { get; set; }
        public string dir_tie { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string cod_dis { get; set; }
        public Nullable<int> id_cat_tienda { get; set; }
        public string cod_usu_tienda { get; set; }
        public Nullable<int> id_pais_tienda { get; set; }
    
        public virtual distrito distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Productoes { get; set; }
        public virtual CATEGORIA_TIENDA CATEGORIA_TIENDA { get; set; }
        public virtual PAI PAI { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
